name: Release
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:

jobs:
  release:
    strategy:
      fail-fast: false
      matrix:
        platform: [macos-latest, ubuntu-22.04, windows-latest]
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable
        with:
          targets: aarch64-apple-darwin

      - name: Install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libappindicator3-dev librsvg2-dev patchelf pkg-config libsoup-3.0-0 libsoup-3.0-dev javascriptcoregtk-4.1 libwebkit2gtk-4.1-dev

      - name: Build macOS App
        if: matrix.platform == 'macos-latest'
        run: |
          cargo install tauri-cli
          cargo tauri build --target aarch64-apple-darwin

      - name: Build Linux App
        if: matrix.platform == 'ubuntu-22.04'
        run: |
          cargo install tauri-cli
          cargo tauri build

      - name: Build Windows App
        if: matrix.platform == 'windows-latest'
        run: |
          cargo install tauri-cli
          cargo tauri build

      - name: Create Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          draft: true
          files: |
            ${{ matrix.platform == 'macos-latest' && 'src-tauri/target/aarch64-apple-darwin/release/bundle/dmg/*.dmg' || '' }}
            ${{ matrix.platform == 'ubuntu-22.04' && 'src-tauri/target/release/bundle/rpm/*.rpm' || '' }}
            ${{ matrix.platform == 'ubuntu-22.04' && 'src-tauri/target/release/bundle/deb/*.deb' || '' }}
            ${{ matrix.platform == 'windows-latest' && 'src-tauri/target/release/bundle/msi/*.msi' || '' }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
